[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "linzens-fsimader-math-tool"
version = "0.1.0"
authors = [
  { name="L0Xit" }
]
description = "Ein simples mathematisches Tool, das keine externen Lizenzen verletzt."
readme = "README.md"
requires-python = ">=3.7"
license = {text = "MIT"}
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = []
